from random import randint

order_id = randint(1000000000000, 999999999999)

order_data = {
            "order_id": order_id,
            "shipping_is_billing": True,
            "order_date": f"{formatted_datetime}",
            "pickup_location": "Home",
            "channel_id": "",
            "comment": "",
            "reseller_name": "Dhruvil",
            "company_name": "",
            "billing_customer_name": user_name,
            "billing_last_name": "",
            "billing_address": order_address,
            "billing_address_2": order_address,
            "billing_isd_code": "",
            "billing_city": user_billing_city,
            "billing_pincode": user_billing_pincode,
            "billing_state": user_billing_state,
            "billing_country": "INDIA",
            "billing_email": user_billing_email,
            "billing_phone": user_billing_phone,
            "billing_alternate_phone": "",
            "shipping_customer_name": "",
            "shipping_last_name": "",
            "shipping_address": "",
            "shipping_address_2": "",
            "shipping_city": "",
            "shipping_pincode": "",
            "shipping_country": "",
            "shipping_state": "",
            "shipping_email": "",
            "shipping_phone": "",
            "order_items": l2,
            "payment_method": "COD",
            "shipping_charges": "0",
            "giftwrap_charges": "0",
            "transaction_charges": "0",
            "total_discount": "0",
            "sub_total": int(order_total) - int((order_total / 100) * 5),
            "length": "30",
            "breadth": "30",
            "height": "7",
            "weight": "{}".format(int(quantity) * 0.4),
            "ewaybill_no": "",
            "customer_gstin": "",
            "invoice_number": "",
            "order_type": ""
        },

return_data = {
            "order_id": id,
            "order_date": "2021-12-30",
            "channel_id": user_data["data"]["channel_id"],
            "pickup_customer_name": ["customer_name"],
            "pickup_last_name": "",
            "company_name": "",
            "pickup_address": ["customer_address"],
            "pickup_address_2": "",
            "pickup_city": ["customer_city"],
            "pickup_state": ["customer_state"],
            "pickup_country": "India",
            "pickup_pincode": ["customer_pincode"],
            "pickup_email": ["customer_email"],
            "pickup_phone": ["customer_phone"],
            "pickup_isd_code": "91",
            "shipping_customer_name": "pyrenean clothing",
            "shipping_last_name": "pyrenean clothing",
            "shipping_address": ["pickup_location"],
            "shipping_address_2": "",
            "shipping_city": "ahmedabad",
            "shipping_country": "India",
            "shipping_pincode": 380060,
            "shipping_state": "GUJARAT",
            "shipping_email": "pyrenean@gmail.com",
            "shipping_isd_code": "91",
            "shipping_phone": 9033474857,
            "order_items": [
                {
                    "sku": "shirt-M-2709",
                    "name": "shoes",
                    "units": 1,
                    "selling_price": user_data["data"]["products"]["price"],
                    "discount": 0,
                    "qc_enable": True,
                    "hsn": "",
                    "brand": "",
                    "qc_size": ""
                }
            ],
            "payment_method": "COD",
            "total_discount": "0",
            "sub_total": 400,
            "length": 30,
            "breadth": 30,
            "height": 7,
            "weight": user_data["data"]["products"]["quantity"] * units
        }