# Generated by Django 4.2.4 on 2023-08-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='kides',
            name='color',
        ),
        migrations.RemoveField(
            model_name='mens',
            name='color',
        ),
        migrations.RemoveField(
            model_name='womens',
            name='color',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kides',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Very Extra Large', 'XXL')], default='Small', max_length=20),
        ),
        migrations.AlterField(
            model_name='mens',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Very Extra Large', 'XXL')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='womens',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Very Extra Large', 'XXL')], default='Medium', max_length=20),
        ),
    ]
