# Generated by Django 4.2.4 on 2023-10-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='gets_id',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='size_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
