# Generated by Django 4.2.4 on 2023-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_data',
            name='address_1',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
