# Generated by Django 4.2.4 on 2023-10-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
