# Generated by Django 4.2.5 on 2023-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0002_remove_cartmodel_gets_id_cartmodel_size_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
