# Generated by Django 4.2.4 on 2023-08-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0002_remove_cartmodel_color_remove_kides_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kides',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mens',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='womens',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
