# Generated by Django 4.2.4 on 2023-10-15 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0003_subscribenow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
