# Generated by Django 4.2.4 on 2023-11-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0003_user_address_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='minimum_price',
            field=models.IntegerField(default=1500),
        ),
    ]
