# Generated by Django 4.2.4 on 2023-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0004_alter_cartmodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='picture',
            field=models.ImageField(upload_to='static/images/CartModules/'),
        ),
    ]
