# Generated by Django 4.2.5 on 2023-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0004_user_data_state_alter_user_data_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('address_1', models.CharField(default='INDIA', max_length=1000)),
                ('products_detail', models.CharField(default='empty', max_length=1000)),
                ('order_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='final_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='INDIA', max_length=1000)),
                ('products_detail', models.CharField(default='empty', max_length=1000)),
                ('order_total', models.IntegerField()),
                ('shiprocket_dashboard', models.BooleanField(default=False)),
            ],
        ),
    ]
