# Generated by Django 4.2.4 on 2023-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0005_promocode_alter_product_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
