# Generated by Django 4.2.4 on 2023-08-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0005_alter_cartmodel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mens',
            name='picture',
        ),
    ]
