# Generated by Django 4.2.4 on 2023-10-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0006_remove_size_kid_remove_size_men_remove_size_women_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='size',
        ),
    ]
