# Generated by Django 4.2.4 on 2023-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0006_remove_mens_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mens',
            name='picture',
            field=models.ImageField(default='', upload_to='static/images/Mens/'),
        ),
    ]
