# Generated by Django 4.2.5 on 2023-10-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0005_alter_contactmodel_email'),
        ('Pyrenean', '0006_promocode_email'),
    ]

    operations = [
    ]
