# Generated by Django 4.2.4 on 2023-08-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0007_mens_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kides',
            new_name='Kid',
        ),
        migrations.RenameModel(
            old_name='Womens',
            new_name='Women',
        ),
    ]
