# Generated by Django 4.2.4 on 2023-10-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0007_remove_product_details_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pyrenean.product_details'),
        ),
    ]
