# Generated by Django 4.2.4 on 2023-08-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0008_rename_kides_kid_rename_womens_women'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='mens',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='women',
            old_name='quantity',
            new_name='max_quantity',
        ),
    ]
