# Generated by Django 4.2.5 on 2023-10-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0008_size_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
        migrations.DeleteModel(
            name='Mens',
        ),
        migrations.DeleteModel(
            name='UniSex',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
