# Generated by Django 4.2.4 on 2023-11-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0008_final_order_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
