# Generated by Django 4.2.4 on 2023-11-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0009_alter_user_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='state',
            field=models.CharField(default='GUJRAT', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='building',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
