# Generated by Django 4.2.4 on 2023-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0009_rename_quantity_cartmodel_max_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kid',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mens',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='women',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
