# Generated by Django 4.2.4 on 2023-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0010_alter_user_address_city_alter_user_address_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='account_email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
    ]
