# Generated by Django 4.2.5 on 2023-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0010_alter_user_address_city_alter_user_address_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='shipment',
            field=models.BooleanField(default=False),
        ),
    ]
