# Generated by Django 4.2.5 on 2023-11-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrenean', '0011_cart_data_shipment'),
        ('Pyrenean', '0011_user_address_account_email'),
    ]

    operations = [
    ]
